service: weather-bot

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    DARK_SKY_API_KEY: ${file(./config.yml):DARK_SKY_API_KEY}
    LATITUDE: ${file(./config.yml):LATITUDE}
    LONGITUDE: ${file(./config.yml):LONGITUDE}
    ACCOUNT_SID: ${file(./config.yml):ACCOUNT_SID}
    ACCOUNT_TOKEN: ${file(./config.yml):ACCOUNT_TOKEN}
    FROM_NUMBER: ${file(./config.yml):FROM_NUMBER}

functions:
  weather:
    handler: handler.run
    events:
      - schedule: cron(0 12 * * ? *)